services:
  - type: web_service
    name: neural-style-transfer
    env: python
    plan: free
    branch: main
    pythonVersion: 3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT